/** Declaration file generated by dts-gen */

export = node_blink1;

declare class node_blink1 {
    constructor(serialNumber: any);

    close(callback: any): void;

    degamma(n: any): any;

    disableServerDown(millis: any, callback: any): void;

    eeRead(address: any, callback: any): void;

    eeWrite(address: any, value: any, callback: any): void;

    enableServerDown(millis: any, callback: any): void;

    fadeToRGB(fadeMillis: any, r: any, g: any, b: any, index: any, callback: any): void;

    getId(callback: any): void;

    getStartupParams(callback: any): void;

    goBootload(callback: any): void;

    off(callback: any): void;

    pause(callback: any): void;

    play(position: any, callback: any): void;

    playLoop(startPosition: any, endPosition: any, count: any, callback: any): void;

    readNote(noteId: any, asString: any, callback: any): void;

    readPatternLine(position: any, callback: any): void;

    rgb(index: any, callback: any): void;

    savePattern(callback: any): void;

    setLedN(index: any, callback: any): void;

    setRGB(r: any, g: any, b: any, callback: any): void;

    setStartupParams(param: any, callback: any): void;

    version(callback: any): void;

    writeNote(noteId: any, noteData: any, callback: any): void;

    writePatternLine(fadeMillis: any, r: any, g: any, b: any, position: any, callback: any): void;

    static Blink1: any;

    static devices(): any;

}

